"""
Validation layer responsible for checking structured order objects returned by the LLM

Responsibilities:
- Verify required order fields are present
- Confirm field types match expected schema
- Reject malformed or incomplete LLM outputs
- Prevent hallucinated or invalid data from reaching filtering logic
- Return only safe, validated order records for downstream processing
"""

import logging

# expected schema definition for structured orders
REQUIRED_FIELDS = {
    "orderID": str,
    "buyer": str,
    "city": str,
    "state": str,
    "total": (int, float),
    "items": list
}

def validate_order(order):
    """
    Validate one structured order object returned by the LLM

    Args:
        order (dict):
            Structured order dictionary generated by llm_service.py

    Returns:
        dict | None:
            Validated order if schema check pass
            None if validation fails
    """

    # defensive validatoin
    # ensure order is actually a dictionary
    if not isinstance(order, dict):
        
        logging.warning(
            "Invalid order: expected dictionary but received %s",
            type(order)
        )

        return None
    
    # iterate through every required schema field
    # REQUIRED_FIELDS.items() returns:
    # field name + expected type
    #
    # example:
    # ("buyer", str)
    for field, expected_type in REQUIRED_FIELDS.items():

        # verify field exists in structured order
        #
        # protects against:
        # - missing LLM fields
        # - incomplete extraction
        # - hallucinated partial responses
        if field not in order:

            logging.warning(
                "Invalid order: missing required field '%s'",
                field
            )

            return None

        # verify field type matches expected schema
        #
        # examples:
        #
        # valid:
        # "buyer": "John Davis"
        #
        # invalid:
        # "buyer": 12345
        #
        # valid:
        # "total": 742.10
        #
        # invalid:
        # "total": "742.10"
        #
        # protects downstream filtering/business logic
        if not isinstance(order[field], expected_type):

            logging.warning(
                "Invalid order: field '%s' has incorrect type. Expected %s but received %s",
                field,
                expected_type,
                type(order[field])
            )

            return None

    # validate state abbreviation format
    #
    # expected examples:
    # OH
    # TX
    # WA
    #
    # invalid examples:
    # Ohio
    # O
    # Ohio123
    #
    # simple schema constraint to improve consistency
    if len(order["state"]) != 2:

        logging.warning(
            "Invalid order: state must be a 2-letter abbreviation"
        )

        return None

    # defensive business-rule validation
    #
    # prevents invalid financial values
    #
    # invalid example:
    # total = -500
    #
    # protects downstream analytics/filtering logic
    if order["total"] < 0:

        logging.warning(
            "Invalid order: total cannot be negative"
        )

        return None

    # if all validation checks pass,
    # return validated safe order object
    return order

def validate_orders(orders):
    """
    Validate multiple structured order objects and return only safe records

    Args:
        order (list):
            List of structured order dictionaries
    
    Returns:
        list:
            List containing only validated orders
    """

    # stores only validated/safe orders
    valid_orders = []

    # iterate through every structured order returned by the LLM
    for order in orders:

        # validate individual order
        validated_order = validate_order(order)

        # skip malformed/invalid orders
        #
        # continue moves to next loop iteration
        #
        # prevents invalid records from entering
        # downstream filtering/business logic
        if validated_order is None:
            continue

        # append validated order to safe results list
        valid_orders.append(validated_order)

    # observability logging:
    # monitor validation success rate
    logging.info(
        "Validated %d out of %d structured orders",
        len(valid_orders),
        len(orders)
    )

    # return validated safe order list
    return valid_orders

        